name: Publish Docker image

on:
  workflow_dispatch:
  push:

jobs:

  gitversion:
    name: get current git version
    runs-on: ubuntu-latest
    outputs:
      majorminorpatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
      semver: ${{ steps.gitversion.outputs.semVer }}
      shortsha: ${{ steps.gitversion.outputs.shortSha }}
      branchname: ${{ steps.gitversion.outputs.branchName }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion

  build-image:
    name: build and upload docker image
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ needs.gitversion.outputs.semver }}
      SHORTSHA: ${{ needs.gitversion.outputs.shortsha }}
      MAJORMINORPATCH: ${{ needs.gitversion.outputs.majorminorpatch }}
      BRANCH: ${{ needs.gitversion.outputs.branchname }}
    needs:
      - gitversion
    steps:

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v3

      - name: run/docker-build-push-develop
        if: contains(env.BRANCH, 'develop') || startsWith(env.BRANCH, 'release') || startsWith(env.BRANCH, 'hotfix') || startsWith(env.BRANCH, 'tags')
        run: |
          docker build . \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/octodns:${{ env.SEMVER }} \
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/octodns:${{ env.SEMVER }}

      - name: run/docker-build-push-main
        if: contains(env.BRANCH, 'main')
        run: |
          docker build . \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/octodns:latest \
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/octodns:latest